
# --- SMART_CONVERSATION_FILTER START ---
def is_valid_terminal_command(text_input):
    clean_text = str(text_input).strip().lower()
    allowed = ['pwd', 'df', 'free', 'systemctl', 'ls', 'top', 'uptime', 'ifconfig']
    if not clean_text: return False
    first_word = clean_text.split()[0]
    if first_word in allowed and len(clean_text.split()) <= 4:
        return True
    return False
# --- SMART_CONVERSATION_FILTER END ---
from pathlib import Path
import json
import re
import subprocess

BASE_DIR = Path("/root/workspaces/customers")

def safe_name(name: str) -> str:
    name = name.strip().lower()
    name = re.sub(r"[^a-z0-9_]+", "_", name)
    name = re.sub(r"_+", "_", name).strip("_")
    if not name:
        raise ValueError("Invalid name")
    return name

def create_customer_bot(bot_type: str, bot_name: str):
    bot_type = safe_name(bot_type)
    bot_name = safe_name(bot_name)

    project = BASE_DIR / bot_name
    project.mkdir(parents=True, exist_ok=True)
    (project / "data").mkdir(exist_ok=True)
    (project / "logs").mkdir(exist_ok=True)
    (project / "backups").mkdir(exist_ok=True)

    (project / "requirements.txt").write_text(
        "python-telegram-bot==21.6\npython-dotenv==1.0.1\nopenai\n",
        encoding="utf-8"
    )

    (project / ".env.example").write_text(
        "BOT_TOKEN=put_customer_bot_token_here\nOPENAI_API_KEY=optional_openai_key_here\n",
        encoding="utf-8"
    )

    (project / "data" / "business.json").write_text(
        json.dumps({
            "bot_name": bot_name,
            "bot_type": bot_type,
            "business_name": "",
            "products": [],
            "services": [],
            "prices": [],
            "faq": []
        }, indent=2),
        encoding="utf-8"
    )

    (project / "README.md").write_text(
        f"# {bot_name}\n\nType: {bot_type}\nGenerated by Sameer AI Manager.\n",
        encoding="utf-8"
    )

    bot_code = f'''import os
from dotenv import load_dotenv
from telegram import Update
from telegram.ext import ApplicationBuilder, CommandHandler, MessageHandler, ContextTypes, filters

load_dotenv()
BOT_TOKEN = os.getenv("BOT_TOKEN")

async def start_cmd(update: Update, context: ContextTypes.DEFAULT_TYPE):
    await update.message.reply_text("✅ {bot_name} customer bot is running.")

async def help_cmd(update: Update, context: ContextTypes.DEFAULT_TYPE):
    await update.message.reply_text("Commands:\\n/start\\n/help\\n/status")

async def status_cmd(update: Update, context: ContextTypes.DEFAULT_TYPE):
    await update.message.reply_text("✅ Service active. Bot name: {bot_name}")

async def reply_msg(update: Update, context: ContextTypes.DEFAULT_TYPE):
    await update.message.reply_text("Thanks. Your message received.")

def main():
    if not BOT_TOKEN:
        raise RuntimeError("BOT_TOKEN missing in .env")
    app = ApplicationBuilder().token(BOT_TOKEN).build()
    app.add_handler(CommandHandler("start", start_cmd))
    app.add_handler(CommandHandler("help", help_cmd))
    app.add_handler(CommandHandler("status", status_cmd))
    app.add_handler(MessageHandler(filters.TEXT & ~filters.COMMAND, reply_msg))
    app.run_polling(drop_pending_updates=True)

if __name__ == "__main__":
    main()
'''
    (project / "bot.py").write_text(bot_code, encoding="utf-8")

    service_file = Path(f"/etc/systemd/system/{bot_name}.service")
    service_file.write_text(f"""[Unit]
Description=Customer Bot {bot_name}
After=network.target

[Service]
WorkingDirectory={project}
ExecStart={project}/venv/bin/python {project}/bot.py
Restart=always
RestartSec=5
Environment=PYTHONUNBUFFERED=1

[Install]
WantedBy=multi-user.target
""", encoding="utf-8")

    cmd = f"""
cd {project}
python3 -m venv venv
{project}/venv/bin/pip install -r requirements.txt
python3 -m py_compile bot.py
systemctl daemon-reload
systemctl enable {bot_name}
systemctl start {bot_name}
"""
    result = subprocess.run(cmd, shell=True, capture_output=True, text=True, timeout=180)
    if result.returncode != 0:
        raise RuntimeError(result.stdout + result.stderr)

    return str(project)
