(()=>{'use strict';const form=document.querySelector('#localized-lead');if(!form)return;const code=document.documentElement.lang;const words=JSON.parse(document.querySelector('#locale-messages').textContent);const btn=form.querySelector('button[type=submit]');const status=document.querySelector('#status');const C='https://portal.freshtiqautomation.com/api/lead';const qs=new URLSearchParams(location.search);
form.addEventListener('submit',async e=>{e.preventDefault();if(form.elements.website.value)return;const name=form.elements.name.value.trim(),phone=form.elements.phone.value.trim(),industry=form.elements.industry.value;const opt=form.elements.opt_in.checked;if(!name||!phone||!industry||!opt){status.className='err';status.textContent=words.valid;return;}btn.disabled=true;btn.textContent=words.sending;status.className='';status.textContent='';
let country=phone.startsWith('+966')?'Saudi Arabia':phone.startsWith('+971')?'United Arab Emirates':phone.startsWith('+91')?'India':'Other country';
try{let sid=sessionStorage.getItem('ft_chat_sid_v2');if(!sid){sid='site_'+Date.now()+'_'+Math.random().toString(36).slice(2,9);sessionStorage.setItem('ft_chat_sid_v2',sid);}
const payload={name,phone,email:'',country,service:'Business automation and WhatsApp / AI / CRM assessment',preferred_contact:'WhatsApp',message:'International business automation enquiry | Locale: '+code+' | Industry: '+industry+' | Please reply in '+code+' | Requested free workflow assessment',source:'Freshtiq International '+code+' Free Assessment',locale:code,session_id:sid,page_url:location.href,landing_page:location.href,referrer:document.referrer||'',utm_source:qs.get('utm_source')||'organic_direct',utm_medium:qs.get('utm_medium')||'',utm_campaign:qs.get('utm_campaign')||'',utm_content:qs.get('utm_content')||'',whatsapp_opt_in:true,marketing_opt_in:false};
const res=await fetch(C,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(payload)});const out=await res.json().catch(()=>({}));if(!res.ok||!out.success)throw Error('CRM rejected');
const ref=out.lead_ref||String(out.lead_id||'');status.className='ok';status.textContent=words.sent;const b=document.createElement('b');b.textContent=ref;b.className='ltr';status.appendChild(b);status.appendChild(document.createTextNode(' · '+words.ref));form.reset();
try{if(typeof window.gtag==='function'){window.gtag('event','generate_lead',{lead_source:payload.source,country,service:payload.service,lead_ref_present:!!ref});window.gtag('event','SUBMIT_LEAD_FORM',{lead_source:payload.source,country,service:payload.service,lead_ref_present:!!ref});}}catch(_e){}
}catch(_e){status.className='err';status.textContent=words.failed;}finally{btn.disabled=false;btn.textContent=words.submit;}});
})();