'use strict';
const assert = require('node:assert/strict');
const vm = require('node:vm');
const fs = require('node:fs');
const path = require('node:path');
const source = fs.readFileSync(path.join(__dirname, '..', 'openai-lead-measurement.js'), 'utf8');
function run(enabled, choice, pathname = '/') {
  const values = new Map(choice ? [['ftq_openai_measurement_consent_v1', choice]] : []);
  const scripts = [];
  let next = 0;
  const w = { location: { pathname }, crypto: { randomUUID: () => 'test-event-' + (++next) } };
  const d = { head: { appendChild: (el) => scripts.push(el) }, createElement: () => ({}) };
  const context = { window: w, document: d, localStorage: { getItem: k => values.get(k), setItem: (k,v) => values.set(k,v) }, Set, Date, Math };
  vm.runInNewContext(enabled ? source.replace("const PIXEL_ID = '';", "const PIXEL_ID = 'synthetic-test-pixel';") : source, context);
  return { w, scripts, values, context };
}
const off = run(false, 'granted');
assert.equal(off.scripts.length, 0);
assert.equal(off.w.FreshtiqOpenAIMeasurement.leadCreated('FTQ-7K4M9Q'), false);
assert.equal(off.w.oaiq, undefined);
const pending = run(true);
assert.equal(pending.scripts.length, 0);
assert.equal(pending.w.FreshtiqOpenAIMeasurement.leadCreated('FTQ-7K4M9Q'), false);
pending.w.FreshtiqOpenAIMeasurement.setConsent(true);
assert.equal(pending.scripts.length, 1);
let calls = pending.w.oaiq.q.map(x => Array.from(x));
assert.equal(calls.filter(x => x[0] === 'measure').length, 0, 'A blocked lead must not replay after consent');
assert.deepEqual(calls[0], ['consent', false]);
assert.equal(calls[1][0], 'init');
assert.equal(pending.w.FreshtiqOpenAIMeasurement.leadCreated('FTQ-8K4M9Q'), true);
assert.equal(pending.w.FreshtiqOpenAIMeasurement.leadCreated('FTQ-8K4M9Q'), false);
calls = pending.w.oaiq.q.map(x => Array.from(x));
const events = calls.filter(x => x[0] === 'measure');
assert.equal(events.length, 1);
assert.equal(events[0][1], 'lead_created');
assert.equal(events[0][2].type, 'customer_action');
assert.equal(events[0][3].opt_out, true);
assert.equal(JSON.stringify(events).includes('FTQ-8K4M9Q'), false, 'CRM reference must not be transmitted');
pending.w.FreshtiqOpenAIMeasurement.setConsent(false);
assert.equal(pending.w.FreshtiqOpenAIMeasurement.leadCreated(4), false);
assert.equal(pending.values.get('ftq_openai_measurement_consent_v1'), 'denied');
assert.equal(pending.w.oaiq.q.at(-1)[1], false);
const granted = run(true, 'granted');
assert.equal(granted.scripts.length, 1);
granted.w.FreshtiqOpenAIMeasurement.leadCreated(5);
assert.equal(granted.w.oaiq.q.filter(x => x[0] === 'measure').length, 1);
vm.runInNewContext(source, granted.context);
assert.equal(granted.scripts.length, 1, 'Duplicate module load must not add another SDK');
for (const pathname of ['/checkout','/customer/123','/privacy.html','/track.html']) {
  const restricted = run(true, 'granted', pathname);
  assert.equal(restricted.scripts.length, 0);
  assert.equal(restricted.w.FreshtiqOpenAIMeasurement.leadCreated(6), false);
  restricted.w.FreshtiqOpenAIMeasurement.setConsent(false);
  assert.equal(restricted.values.get('ftq_openai_measurement_consent_v1'), 'denied');
}
granted.w.oaiq = () => { throw new Error('Synthetic SDK failure'); };
assert.doesNotThrow(() => granted.w.FreshtiqOpenAIMeasurement.leadCreated(7));
assert.equal(granted.w.FreshtiqOpenAIMeasurement.leadCreated(8), false);
assert.doesNotThrow(() => granted.w.FreshtiqOpenAIMeasurement.setConsent(false));
assert.equal(granted.values.get('ftq_openai_measurement_consent_v1'), 'denied');
console.log('PASS: no pixel/no consent, no replay, deduplication, withdrawal, saved consent, sensitive-page exclusions, SDK failure isolation and no CRM-reference transmission; all data synthetic.');
